server.port=8081
spring.application.name=serveur

jwt.secret=ChangeThisSecretKeyInProductionEnvVariable123456789
jwt.expiration=3600000

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/conv_arepo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect